name: Build and Deploy Jekyll Site

on:
  push: main
  pull_request: main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-to-server:

    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy via rsync
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PORT: ${{ secrets.PORT }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${PORT:-22} -H $HOST >> ~/.ssh/known_hosts

          # Deploy with rsync
          rsync -avz --delete \
            -e "ssh -p ${PORT:-22}" \
            _site/ \
            $USERNAME@$HOST:$TARGET_DIR

          # Cleanup
          rm -rf ~/.ssh
